### ISSUE TITLE
migrate documentation to sphinx

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#109] opened 2022-11-17 09:39 UTC
had a brief conversation with @emily-bicks after the weekly review who mentioned that with sphinx, the documentation should automatically update when your code does - although she's having currently issues with this.

**Comment by emily-bicks** [comment] 2022-11-17 10:18
Just to clarity, getting the docs to update automatically is relatively simple, the issue is managing it with source control when hosting it on github pages. Specifically, there are a lot of html files requires to generate all of the different pages, which need to be tracked on github if the docs are hosted on pages, and am having issues with merge conflicts as people are updating things on different branches. If you guys come up with a good solution to this please let me know! Here are some resources on getting started with setting [sphinx up for your project, ](https://www.sphinx-doc.org/en/master/usage/quickstart.html) and [automatically generating documentation from docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). Also - if this is a cookiecutter project sphinx should actually already be configured for you and you can just run 'make docs' (although there are likely some bugs with it).

**Comment by Aiden-RC** [comment] 2022-11-17 16:47
> Just to clarity, getting the docs to update automatically is relatively simple, the issue is managing it with source control when hosting it on github pages. Specifically, there are a lot of html files requires to generate all of the different pages, which need to be tracked on github if the docs are hosted on pages, and am having issues with merge conflicts as people are updating things on different branches. If you guys come up with a good solution to this please let me know! Here are some resources on getting started with setting [sphinx up for your project, ](https://www.sphinx-doc.org/en/master/usage/quickstart.html) and [automatically generating documentation from docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). Also - if this is a cookiecutter project sphinx should actually already be configured for you and you can just run 'make docs' (although there are likely some bugs with it).

Github actions would be a good solution to this if you can set it up correctly.
https://github.com/marketplace/actions/sphinx-build
Using an action like the one above ( or making your own ) that can build the documentation and then push the changes to the github pages.
Trigger the action on the main branch commit / pr merged to auto build the documentation and that should elimenate any merge conflicts as it'll be building from a single source.
( could also nuke the html files from existence and rebuild every time aswell )

In my case we also use sphinx but i've got mine setup to push to one of our remote servers and build remotely and host it through apache.

Hope this helps in some way :)

**Comment by lizgzil** [comment] 2022-12-05 15:25
done

**Closed as completed by lizgzil** 2022-12-05 15:25 UTC
